# Generated by Django 4.2.9 on 2024-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
    ]
