# Generated by Django 4.2.9 on 2024-01-11 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0005_alter_orderrow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrow',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique service ID', primary_key=True, serialize=False),
        ),
    ]
